schema_version = "1.0.0"

id = "pinned_modifiers"
version = "1.0.0"
name = "Pinned Modifiers"
tagline = "Pins favorite modifiers to the Add Modifier menu"
maintainer = "Francesco Yoshi Gobbo <dev@furayoshi.com>"
type = "add-on"
website = "https://github.com/FraYoshi/blender-pinned-modifiers"
tags = ["User Interface", "Modeling"]
blender_version_min = "4.3.0"
license = ["SPDX:GPL-3.0-or-later"]

[permissions]
files = "Save and load custom pinned modifiers preferences"

[build]
paths_exclude_pattern = [
  ".git",
  "media",
  "releases",
  ".github",
  ".gitattributes",
  ".gitignore",
  "*.zip",
]